# Generated by Django 2.0.8 on 2018-08-16 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('style', models.CharField(max_length=200)),
                ('room_type', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('designer_note', models.CharField(max_length=200)),
                ('final_note', models.CharField(max_length=200)),
                ('revision_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
