# Generated by Django 2.0.8 on 2018-08-17 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(choices=[('BEDROOM', 'Bedroom'), ('LIVING_ROOM', 'Living Room'), ('MULTIPURPOSE_ROOM', 'Open Layout'), ('STUDIO', 'Studio'), ('DINING_ROOM', 'Dining Room'), ('HOME_OFFICE', 'Office')], max_length=100)),
                ('status', models.CharField(choices=[('DETAILS', 'Details'), ('DESIGN', 'Design'), ('CONCEPTS', 'Concepts'), ('FLOOR_PLAN', 'Floor Plan'), ('REQUEST_ALTERNATIVES', 'Request Alternatives'), ('ALTERNATIVES_READY', 'Alternatives Ready'), ('FINAL_DELIVERY', 'Final Delivery'), ('SHOPPING_CART', 'Shopping Cart'), ('ESTIMATE_SHIPPING_AND_TAX', 'Estimate Shipping & Tax'), ('CHECKOUT', 'Checkout'), ('ARCHIVED', 'Archived')], max_length=100)),
                ('shared_with', models.CharField(choices=[('MYSELF', 'Myself'), ('PARTNER', 'Partner'), ('ROOMMATE', 'Roommate(s)'), ('FAMILY', 'Family')], max_length=100)),
                ('budget', models.CharField(choices=[(1, '$2k or less'), (2, '$2k - $4k'), (3, '$4k - $6k'), (4, '$4k or more')], max_length=1)),
                ('pet_friendly', models.BooleanField(default=True)),
                ('limited_access', models.BooleanField(default=False)),
                ('style', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('designer_note', models.CharField(max_length=200)),
                ('final_note', models.CharField(max_length=200)),
                ('revision_count', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
