# Generated by Django 2.0.8 on 2019-04-14 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='details')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], max_length=100)),
                ('type', models.CharField(choices=[('DRAWING', 'Drawing'), ('INSPIRATION', 'Inspiration'), ('FURNITURE', 'Existing Furniture'), ('CONCEPT', 'Concept'), ('FLOOR_PLAN', 'Floor Plan'), ('FINAL_SNAPSHOT', 'Final Snapshot')], max_length=100)),
            ],
        ),
    ]
