# Generated by Django 2.0.8 on 2018-08-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_projectitem_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='lng',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
